In [1]:
import pandas as pd
from faker import Faker

import warnings
df = pd.read_csv('CEP_unid_correios.csv')
cep=df['CEP']

cep.shape

(5436,)

In [36]:
a=cep.sample(n=1)

def fake_name_email():
    
    fake = Faker('pt_BR')
    # Lista de gêneros possíveis
    generos = ['M', 'F']
    # Escolhe um gênero aleatório
    genero = random.choice(generos)
    # Gera o primeiro nome conforme o gênero escolhido
    if genero == 'M':
        primeiro_nome = fake.first_name_male()
    else:
        primeiro_nome = fake.first_name_female()

    sobrenome = fake.last_name()
    
    nome = f"{primeiro_nome} {sobrenome}"
    #nome = fake.name()
    titulos = ['sra.','srta.', 'sr.', 'dr.', 'dra.','dom']

    nomes = nome.lower().split()
    email_base = ''
    nome_base=''
    if nomes[0] in titulos:
        if len(nomes) >= 3:
            email_base = f"{nomes[1]}.{nomes[-1]}"
            nome_base = nomes[1]+' '+nomes[-1]
        else:
            email_base = '.'.join(nomes[1:])
            nome_base = f"{nomes[1]}"
    else:
        if len(nomes) >= 2:
            email_base = f"{nomes[0]}.{nomes[-1]}"
            nome_base = nomes[0]+' '+nomes[-1]
        else:
            email_base = nomes[0]
            nome_base = f"{nomes[1]}"
        
    return nome_base,email_base+'@email.com',genero
            
dados=[]
for i in range(1,200):
    nome_base,email_base,genero=fake_name_email()
    data_nascimento = fake.date_of_birth(minimum_age=18, maximum_age=90)

    U={'id': i,
       'nome':nome_base,
       'email':email_base,
       'telefone': fake.cellphone_number(),
       'cep': cep.sample(n=1).values[0],
       'data_nascimento':data_nascimento.strftime("%d-%m-%Y"),
       'genero':genero}
    dados.append(U)


df = pd.DataFrame(dados)
df

,id,nome,email,telefone,cep,data_nascimento,genero
0,1,emanuelly vieira,emanuelly.vieira@email.com,+55 (75) 99576 0226,12345-678,18-12-1954,F
1,2,isis pastor,isis.pastor@email.com,+55 (072) 97218 4567,54321-123,25-09-1948,F
2,3,raquel souza,raquel.souza@email.com,+55 (034) 93630-4636,98765-432,13-10-1962,F
3,4,maria silveira,maria.silveira@email.com,+55 (003) 93431-9102,98765-432,26-07-1988,F
4,5,cauã monteiro,cauã.monteiro@email.com,+55 (089) 97393-9187,98765-432,17-02-1954,M
...,...,...,...,...,...,...,...
194,195,valentim sales,valentim.sales@email.com,+55 (43) 97925 5200,54321-123,06-10-1956,M
195,196,bernardo peixoto,bernardo.peixoto@email.com,+55 (38) 99296 3305,54321-123,25-11-1960,M
196,197,ágatha ribeiro,ágatha.ribeiro@email.com,+55 10 9 2127 8924,98765-432,28-04-1937,F
197,198,ágatha moreira,ágatha.moreira@email.com,+55 (042) 99626-9693,98765-432,26-08-1992,F
198,199,maria peixoto,maria.peixoto@email.com,+55 (044) 90985 2471,98765-432,28-10-1937,F

In [37]:
#df.to_csv('users.csv', index=False, encoding='utf-8')

In [44]:
dfa = pd.read_csv('CEP_unid_2.csv')
dfa['CEP DE'].unique()

array([69900000, 69945000, 69935000, ..., 77743000, 77860000, 77880000])